### ISSUE TITLE
Questions about translation process

### ISSUE THREAD

**Issue by IgorMunizS** [taolusi/chisp#6]
Hi! Nice work translating Spider dataset into chinese language.

I'm trying to do the same for another language, can you share some tips?
I've read your paper, but isn't clear if you have used some tool or API to translate and after did a manual verification/correction or translated manually all dataset. 

I would appreciate if you could describe a little more about the whole process.

Thanks!

**Comment by taolusi** [comment]
> 
> 
> Hi! Nice work translating Spider dataset into chinese language.
> 
> I'm trying to do the same for another language, can you share some tips?
> I've read your paper, but isn't clear if you have used some tool or API to translate and after did a manual verification/correction or translated manually all dataset.
> 
> I would appreciate if you could describe a little more about the whole process.
> 
> Thanks!

Hi. Thank you for your attention to our work.

For machine translation, Baidu Translate API is used. It is free in a certain amount of sentences while you need to create your own account to use it. We can share the script if you need it.
For human translation, we have three people to translate the whole dataset first. Then, for each part, another person is asked to check all translated sentences in that part. Note that each person is asked to translate based not only on the original sentence but also the SQL query since it might be difficult to understand the original sentences.

Hope this can be useful to you.
